// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yhoepbasncnivuuzfvoy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlob2VwYmFzbmNuaXZ1dXpmdm95Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2MzExMDMsImV4cCI6MjA3MjIwNzEwM30.DG9iUK0oeylO2C9jJ50nJGnXbJnGcL1SMIRDzAwtb9o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});